apiVersion: apps/v1
kind: Deployment
metadata:
  name: p18
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p18
  template:
    metadata:
      labels:
        app: p18
    spec:
      containers:
      - image: dorowu/ubuntu-desktop-lxde-vnc:focal-lxqt
        name: p18
        ports:
        - containerPort: 80
